In [1]:
#FACE DETECTION
import cv2

In [2]:
img=cv2.imread('F:\\cr1.jpg',1)

In [3]:
print(img)

[[[102  75  71]
  [101  74  70]
  [ 98  73  69]
  ...
  [ 38  32  33]
  [ 38  32  33]
  [ 38  32  33]]

 [[100  73  69]
  [ 97  72  68]
  [ 96  71  67]
  ...
  [ 38  32  33]
  [ 38  32  33]
  [ 37  31  32]]

 [[ 94  69  65]
  [ 93  68  64]
  [ 92  67  63]
  ...
  [ 37  31  32]
  [ 37  31  32]
  [ 37  31  32]]

 ...

 [[  0   0  61]
  [  2   0  74]
  [ 17   3 108]
  ...
  [  0   0 139]
  [ 19   1 168]
  [ 49  34 195]]

 [[  0   3  54]
  [  3   0  69]
  [ 18   4 106]
  ...
  [ 28   3 183]
  [ 34  10 198]
  [ 34  12 194]]

 [[  0   3  54]
  [  3   0  69]
  [ 18   4 106]
  ...
  [ 46  21 201]
  [ 36  12 200]
  [ 20   0 180]]]


In [4]:
print(img.shape)

(275, 183, 3)


In [8]:
cv2.imshow('Ronaldo',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
face_cascade=cv2.CascadeClassifier('F:\\haarcascade_frontalface_default.xml')

In [4]:
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=face_cascade.detectMultiScale(gray_img,scaleFactor=1.05,minNeighbors=5)
print(type(faces))
print(faces)
for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
resized=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0])))



<class 'numpy.ndarray'>
[[20 20 93 93]]


In [6]:
cv2.imshow('Gray',resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

-1